## plugins for rust ##
[[plugins]]
repo = "rust-lang/rust.vim"
hook_add = '''
let g:rustfmt_command = 'rustfmt +nightly'
let g:rustfmt_autosave = 1
let g:rustfmt_autosave_if_config_present = 1
let g:rust_recommended_style = 0
'''
on_ft = ["rust"]

# [[plugins]]
# repo = "sakhnik/nvim-gdb"
# hook_source = """
# " We're going to define single-letter keymaps, so don't try to define them
# " in the terminal window.  The debugger CLI should continue accepting text commands.
# function! NvimGdbNoTKeymaps()
#   tnoremap <silent> <buffer> <esc> <c-\><c-n>
# endfunction
# 
# nnoremap <leader>rd :GdbStart rust-gdb -q target/debug
# 
# let g:nvimgdb_config_override = {
#   \ 'key_next': 'n',
#   \ 'key_step': 's',
#   \ 'key_finish': 'f',
#   \ 'key_continue': 'c',
#   \ 'key_until': 'u',
#   \ 'key_breakpoint': 'b',
#   \ 'set_tkeymaps': "NvimGdbNoTKeymaps",
#   \ }
# """

# ## plugins for python ##
# [[plugins]]
# repo = 'aliev/vim-compiler-python'
# on_ft = ["python"]
# 
# [[plugins]]
# repo = 'tpope/vim-dispatch'
# on_ft = ["python"]
# 
# [[plugins]]
# repo = 'janko-m/vim-test'
# depends = ['vim-dispatch']
# hook_add = '''
# let g:test#strategy = 'dispatch'
# '''
# on_ft = ["python"]


[[plugins]]
repo = "Vimjas/vim-python-pep8-indent"
on_ft = ["python"]


# ## plugins for javascript ##
# [[plugins]]
# repo = "pangloss/vim-javascript"
# on_ft = ["javascript"]


## plugins for R ##
# [[plugins]]
# repo = "jalvesaq/Nvim-R"
# hook_add = '''
# vmap <leader><Space> <Plug>RDSendSelection
# nmap <leader><Space> <Plug>RDSendLine
# let g:R_app = "radian"
# let g:R_cmd = "R"
# let R_hl_term = 0
# let R_args = ["--no-history"]
# let g:R_assign = 0
# let g:R_objbr_opendf = 0
# let g:R_insert_mode_cmds = 1
# let g:r_indent_align_args = 1
# let g:R_rconsole_width = 0
# let g:R_parenblock = 1
# '''
# on_ft = ["r", "R"]

[[plugins]]
repo = 'eigenfoo/stan-vim'
on_ft = ["stan"]

## plugins for toml ##
[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]]
repo = 'delphinus/vim-toml-dein'
on_ft = ["toml"]

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ["html", "md"]
